version: '2'
services: 
  app:
    image: busybox
    tty: true
    volumes: 
    - ./:/usr/share/nginx/sonerezh

  nginx:
    image: nginx
    volumes: 
    - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports: 
    - "8080:80"
    links: 
    - php
    volumes_from: 
    - app

  php:
    #image: php:7-fpm
    build:
      context: .docker
      dockerfile: Dockerfile-php
    links: 
    - db:mysql
    volumes_from: 
    - app
    volumes:
    - ./musics:/musics
    #- .docker/database.php:/usr/share/nginx/sonerezh/app/Config/database.php

  db:
    image: mysql:5.7
    environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_USER=sonerezh
    - MYSQL_PASSWORD=sonerezh
    - MYSQL_DATABASE=sonerezh
    volumes: 
    - ./db:/var/lib/mysql 